### ISSUE TITLE
Unhanded rejections when Cloning

### ISSUE THREAD

**Issue by gjsmith66** [CenturyLinkCloud/clc-node-sdk#195]
I have been trying to get serverService.Clone to work.  I am finding that not all potential errors seems to be handled well, here is an example. 

Unhandled rejection TypeError: Cannot read property 'cpu' of undefined
    at CreateServerConverter.self.convertMachine (/Users/Eagle/server/node_modules/clc-node-sdk/clc-sdk.js:5229:42)
    at tryCatcher (/Users//Eagle/server/node_modules/clc-node-sdk/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/Eagle/server/node_modules/clc-node-sdk/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users//Eagle/server/node_modules/clc-node-sdk/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/Users//Eagle/server/node_modules/clc-node-sdk/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/Users//Eagle/server/node_modules/clc-node-sdk/node_modules/bluebird/js/main/async.js:177:16)
    at Async._drainQueues (/Users//Eagle/server/node_modules/clc-node-sdk/node_modules/bluebird/js/main/async.js:187:10)
    at Async.drainQueues (/Users//Eagle/server/node_modules/clc-node-sdk/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickDomainCallback (node.js:492:13)

My Clone function does have a .Catch, but it is not getting called when the above error occurs.  This seems to happen with a variety of other errors that the Clone function can generate.

I am also getting the following error, which is odd since a server with 16 servers is easily cloned from our Control Portal...

{ message: 'CPU limit exceeded -> available: 9, requested: 16' }
The operation *Clone Server* was failed:
The request was failed Error: Cannot POSTJSON https://api.ctl.io/v2/xxxxxx. Details: {"message":"CPU limit exceeded -> available: 9, requested: 16"}

**Comment by push1st1k** [comment]
@gjsmith66 Could you please provide the server config you pass to `clone` function?

**Comment by gjsmith66** [comment]
Thanks.  I will see if I can find example that causes the unhanded exception.  However, it was in response to the request to the CL API failing.  The second issue was user error.
